### ISSUE TITLE
Page selector on DataTablePagination component is not suitable for tables with many pages

### ISSUE THREAD

**Issue by sharon-oboyle** [carbon-design-system/ibm-security#162]
## Bug - 
The page selector on https://pages.github.ibm.com/security/carbon-addons-security/branch/v2/?path=/story/components-datatablepagination--pagination-data-table component that we are using in ISC Cases app is unsuitable when there are many pages in the table - would it be possible to use a different component?

**Expected behavior -**

User should be able to enter a number to select the page via, for example, a text field or a number input component

**Actual behavior -**

The control is a Select inside the Pagination component, and when there are many pages the it is  displayed outside the confines of the browser page, and user has to scroll up and down to find the required page and then select it.  This is not an acceptable User Experience.

### Steps for reproducing

1.  Create around 650 entries in the data table pagination table 
2.  Select 10 items per page
3.  Click on the page selector and observe it's behaviour when trying to select a page, say page 60

### Affected browsers
All browsers, but worse on Chrome (as shown in screenshot)

**Comment by SimonFinney** [comment]
I would be inclined to say that this is something that we should affect on our level - I would suggest creating this issue in https://github.com/carbon-design-system/carbon to discuss a solution there.

**Comment by sharon-oboyle** [comment]
Have done here, thanks! https://github.com/carbon-design-system/carbon/issues/4365

**Comment by jendowns** [comment]
I had an idea for this one so I opened a PR here: https://github.com/carbon-design-system/carbon/pull/4378

If Carbon is okay with this approach, it would involve passing in a number via a prop that would control the height of the `select` list box. For example, if you set it to `5`, it would look like this:

![Screen Shot 2019-10-17 at 4 18 54 PM](https://user-images.githubusercontent.com/9057921/67048823-8aa3ed80-f0fa-11e9-8599-286f82b75b17.png)

**Comment by jendowns** [comment]
Work on this is now dependent on #223

**Comment by jendowns** [comment]
Dependent on #295 295

**Comment by JasonKeirstead** [comment]
The ability to arbitrarily select pages is not a useful ability because it implies that the user has some kind of sixth sense as to what page they want to view. No clients ever use it.

Should look to how Google GUI does pagination for inspiration on how to deal with large result sets... you show the first bunch, and sometimes the last page and thats really all that matters....

I would argue the ability should just be entirely removed

**Comment by jendowns** [comment]
@JasonKeirstead The `UNSTABLE__Pagination` component that I added does give you the ability to leave out a the page selector entirely. Issues linked above relate to this work.

The experimental component is live here: https://ibm-security.carbondesignsystem.com/?path=/story/components-unstable-pagination--with-no-page-selector-or-sizer

**Comment by jendowns** [comment]
I'm going to close out this issue because technically the original request has been fulfilled -- we now have a component, currently called `UNSTABLE__Pagination`, that allows you to leave out the inner "page selector" element. Without this element, you don't have to worry about the select. The component has the `UNSTABLE__` prefix because it is considered experimental until the next major release, `2.0`, which will be forthcoming around the end of March.

Here is an example of this new pagination component without the page selector: https://ibm-security.carbondesignsystem.com/?path=/story/components-unstable-pagination--with-no-page-selector-or-sizer

If you still want to keep the page selector for some reason, but are bothered by the select options height, you can pass in a `size` attribute to the `PageSelector` child. That `PageSelector` is merely a `select` HTML element, so you can use `size={5}` to limit the height of the options list to give lines, for example. Details here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#attr-size

As linked above, there will be an upcoming number input option (which can be used instead of the `PageSelector` child) but that will be a non-breaking feature. (for details: https://github.com/carbon-design-system/ibm-security/issues/295)

Please let me know if you have any questions. Closing now. 👍
