### ISSUE TITLE
DataTableSkeleton won't work without importing DataTable

### ISSUE THREAD

**Issue by clairek20** [carbon-design-system/ibm-security#300]
## Bug - So it appears that the `DataTableSkeleton` will not work if the file does not also have `DataTable`. See error below:
![image](https://user-images.githubusercontent.com/55839633/72083860-61aa8780-32fa-11ea-9dc1-cfa22ffbceb4.png)
I did a test where i then put the `DataTableSkeleton` in a file where there was a `DataTable` and it worked without any issue

**Expected behavior -**
That you can use the skeleton without having to have a dataTable imported also.

**Actual behavior -**
`DataTableSkeleton` not usable currently if `DataTable` isn't in the file

### Steps for reproducing
Import DataTableSkeleton alone and it will cause issues

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

- [ ]  / 
- [ ]  / 
- [ ]  / 

### Optional information

**Version -**

**Comment by jendowns** [comment]
@clairek20 Taking a quick look at this... using the latest version `1.13.0`, I took the CodeSandbox example and just imported the `DataTableSkeleton` by itself -- https://codesandbox.io/s/codesandbox-2ene9

```jsx
import { DataTableSkeleton } from "@carbon/ibm-security";

import React, { Fragment } from "react";
import { render } from "react-dom";

import "@carbon/ibm-security/css/index.min.css";

const App = () => (
  <Fragment>
    <DataTableSkeleton />
  </Fragment>
);

render(<App />, document.getElementById("root"));
```

And it rendered just fine in the example. 🤔 
So maybe what you are experiencing is something unique to your environment? This error `Module "@carbon/ibm-security" has no exported member 'DataTableSkeleton` looks like a TypeScript error, in particular.

### A couple debugging questions...
1. What version of `@carbon/ibm-security` are you using?
2. Does it work when you import more directly, not just from the index file? So what happens when you do `import { DataTableSkeleton } from "@carbon/ibm-security/es/components/DataTable";`?
3. Do you have multiple TypeScript files with similar names that are using `DataTableSkeleton`, like a `example.ts` and `example.tsx` structure where the files have the same "name" but `ts` vs `tsx` extensions?

**Comment by clairek20** [comment]
Thanks so much for looking @jendowns 
That's interesting, i do think it's a bit strange as i did see it working and then it just broke with that error. I'm starting to think it might be my environment alright.

So to answer your questions:
1: Using version 1.13.0
2: I tried importing more directly as above and i got this error: 
`Could not find a declaration file for module '@carbon/ibm-security/es/components/DataTable'. '/Users/clairekingston/Documents/clx/console/node_modules/@carbon/ibm-security/es/components/DataTable/index.js' implicitly has an 'any' type.`
2: We aren't using multiple tsx files with similar names, and we aren't using `DataTableSkeleton` anywhere else either

**Comment by jendowns** [comment]
Thank you @clairek20! This has me stumped... would you mind linking me (in Slack 😅 ) to a branch where you tried to use `DataTableSkeleton` in your project & saw these errors?

**Comment by clairek20** [comment]
Hi @jendowns 

So found the issue, it needed to be declared inside https://github.ibm.com/SecurityCloud/console/blob/development/src/types/carbon-addons-security.d.ts in order to use it! 
Thanks a million for looking into it anyway, really appreciate it! :) 

Thanks, Claire.
