### ISSUE TITLE
fix: pagination component, forward button rendered in black instead of white

### ISSUE THREAD

**Issue by joemc11** [carbon-design-system/ibm-security#613]
## Bug - 
Pagination svg buttons are appearing in black instead of white in theme $carbon--theme--g10
**Expected behavior -**
Expect svg pagination buttons to be rendered in white.

**Actual behavior -**
Svg pagination buttons are being rendered in black.

### Screenshots
<img width="896" alt="pagination-white_buttons" src="https://user-images.githubusercontent.com/14826627/84643621-00649100-aef6-11ea-9811-49fcad830eb7.png">
<img width="885" alt="pagination-black buttons" src="https://user-images.githubusercontent.com/14826627/84643269-8502df80-aef5-11ea-8398-d4a9fbbb4b97.png">

### Affected browsers
All browsers

### Optional information

Example markup is attached.  For pagination black buttons removing fill="currentColor changes the colour of the svg to white

[PaginationMarkup.txt](https://github.com/carbon-design-system/ibm-security/files/4779495/PaginationMarkup.txt)

**Comment by jendowns** [comment]
@joemc11 The `Pagination` does not use `currentColor` for svg fill, as far as I can tell.

Are you referring to the `UNSTABLE__Pagination` component? That component uses `currentColor` for svg fill.

Either way, is the text color in your app not set to white?

**Comment by joemc11** [comment]
We use both UNSTABLE__Pagination and Pagination. The source file is https://github.ibm.com/QRadar/qradar-ui/blob/develop/packages/qradar-user-interface/src/components/custom/LazyLoadTable/LazyLoadTable.js.  The pagination buttons were appearing as white but about a week ago, they are now rendered in black.

**Comment by jendowns** [comment]
Thank you @joemc11. Which one of those components has the svg fill color issue? They use different style sheets.

Also: you say "about a week ago" this occurred? Can you please provide more information about that? Does that mean, for example, that you upgrade versions? Can you please provide version information? Thank you.

**Comment by joemc11** [comment]
Pagination is the component with the current problem.  We are on version 1.20.0 of @carbon/ibm-security, I also tried latest version 1.25.0 and the problem also occurs.

**Comment by jendowns** [comment]
The interesting thing about the `Pagination` component is that we don't control the styles for it.

We import from our upstream library (even before v1.20.0): https://github.com/carbon-design-system/ibm-security/blob/dev/src/components/Pagination/_index.scss#L7

And Carbon sets the fill color here: 
https://github.com/carbon-design-system/carbon/blame/6731445b18157e5b915a05a7d473c46063af1edf/packages/components/src/components/pagination/_pagination.scss#L134

It looks like the icon button itself, which is used by `Pagination`, is defined here with `currentColor` as the default for icon color (5th argument in the mixins): https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/button/_button.scss

(Which means that, when this icon button is used in the `Pagination`  component, the `currentColor` fill becomes `$ui-05` which is white for g100 themes -- again, refer to: https://github.com/carbon-design-system/ibm-security/blob/dev/src/components/Pagination/_index.scss#L7)

So anyway I believe this all indicates that no recent changes happened to icon buttons, and specifically to the variation used in `Pagination`. 

For your situation, **I'd say that means your codebase is overriding fill color by setting a color  with higher specificity than the `Pagination` styles, so that it is picked up by `currentColor` set on the inner icon svg.** I suggest inspecting the `Pagination`'s icon button in your app closely in your browser's console to see what `color` rule is causing the issue. (Again, I imagine high enough specificity would override the color set by `Pagination` styles, which in turn sets the svg's `currentColor`.) Of course it's also possible there's a `fill` rule doing the overriding this. Hard to tell without a screenshot of all styles applied to the icon element. 😅 

As shown in the linked source files above, it looks like nothing has really changed in our upstream library for these styles in many months.

**Comment by joemc11** [comment]
Attached is a screenshot of the styling for the black pagination buttons and the source code resides at https://github.ibm.com/QRadar/qradar-ui/blob/develop/packages/qradar-user-interface/src/components/custom/LazyLoadTable/LazyLoadTable.js
<img width="1155" alt="BlackPaginationButton" src="https://user-images.githubusercontent.com/14826627/84823616-8e379d80-b016-11ea-9e15-83c41035e673.png">

**Comment by jendowns** [comment]
Hey @joemc11 thank you for the screenshot — however you are viewing the “computed” tab which isn’t super useful for us to track this down. We can already see the color in the UI already, so seeing that the color is also computed isn’t quite what we need. 😅

We’d find more info to help debug this in the “styles” tab — when you scroll up and down that tab, you can see all of the styles being applied, including which styles are overriding others.

**Comment by joemc11** [comment]
Hey @jendowns attached is a screenshot showing the styles tab.
<img width="1165" alt="paginationStyles" src="https://user-images.githubusercontent.com/14826627/84868433-98888480-b074-11ea-91e3-ff489b6e90f6.png">

**Comment by SimonFinney** [comment]
@joemc11 / @jendowns - Can either of you confirm if this issue has been resolved, or what the current status is?

**Comment by jendowns** [comment]
Hey @SimonFinney I do not have any additional info on this, and I am not able to reproduce it (nor have I seen a reproduced demo).

Unfortunately in the partial screenshot above, it is still unclear where a color is being set that would affect `currentColor`.

**Comment by joemc11** [comment]
Hey guys ping me if you are free today and we can jump on a webex and I will reproduce.  I will be out from 8-17 July.  We have upgraded to 1.26.0 and we are still seeing the black pagination buttons.  My slack display name is joe.mcerlean and email is joe.mcerlean@uk.ibm.com

**Comment by SimonFinney** [comment]
I believe this can be resolved by `@carbon/ibm-security` upgrading to Carbon `v10.13.0` where the pagination buttons now use icon-only ghost buttons instead of a custom solution - https://github.com/carbon-design-system/carbon/releases/tag/v10.13.0

**Comment by joemc11** [comment]
Thanks Simon confirming this in now working in our repo for version 1.28.0.
