### ISSUE TITLE
On click of OverflowMenu , the menu is not coming up in the latest version 1.28.0

### ISSUE THREAD

**Issue by IshratPahalwi** [carbon-design-system/ibm-security#712]
### Description

On upgrading the ibm-security to v1.28.0, it was found that on click of OverflowMenu , the menu is not coming up . Also, I see the following warning at the console :
React does not recognize the `selectorPrimaryFocus` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `selectorprimaryfocus` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by OverflowMenuItem)
    in li (created by OverflowMenuItem)
    in OverflowMenuItem (at ComboButton.js:38)
    in ul (created by FloatingMenu)
    in FloatingMenu (created by OverflowMenu)
    in button (created by ClickListener)
Not too sure if the warning has to do anything with the actual issue.

Expected behavior:
On click of the OverflowMenu, the menu should come up: 
<img width="324" alt="expected_behaviour" src="https://user-images.githubusercontent.com/63109531/89319267-42889400-d656-11ea-931b-9b956293402a.png">

Actual behaviour:
On click of the OverflowMenu, the menu does not come up: 
<img width="322" alt="actual_behaviour" src="https://user-images.githubusercontent.com/63109531/89319589-b6c33780-d656-11ea-8583-9a602020d57b.png">

**Comment by SimonFinney** [comment]
It feels like a prop is getting spread somewhere it shouldn't, but I'd have to dig in a bit - @jendowns what are your thoughts?

**Comment by jendowns** [comment]
Hey @SimonFinney & @IshratPahalwi --

It looks like this issue is related to the `ComboButton` and a recent change: https://github.com/carbon-design-system/ibm-security/pull/684 In that PR, the`selectorPrimaryFocus` was removed as a prop of `OverflowMenuItem` (it wasn't doing anything) and added to `OverflowMenu` (or in this case, `ComboButton`) instead. That prop takes a selector and can be used to set the initial focus when you open the `ComboButton`'s inner `OverflowMenu`.

I put an example `ComboButton` here with two variations, showing the `ComboButton` with and without a `selectorPrimaryFocus` prop: https://codesandbox.io/s/hungry-pond-0tb98 (I suggest opening this in Chrome & refreshing the page if the app appears "blank" at first.)

- The first example does not have `selectorPrimaryFocus` set, so when you open the overflow menu in the `ComboButton`, your focus should go to the first item.
- The second example has `selectorPrimaryFocus` set. It includes a specific selector (a class name) so that "Item 3" will have focus when you open the `ComboButton`'s overflow menu.

@IshratPahalwi I'm wondering if either of these examples match your implementation in your application?
I can see how the prop warning would appear, as it is applied to the inner `ComboButtonItem`/`OverflowMenuItem`; the PR #684 from the latest changed that prop. But I'm not sure why the menu would not open when clicked, so maybe there is something else going on. 🤔 Are you able to reproduce this in CodeSandbox?

**Comment by IshratPahalwi** [comment]
We have our own ComboButton version which uses the OverflowMenu.

**Comment by jendowns** [comment]
I spoke to @IshratPahalwi in Slack about this, but just to document some notes here:

Since this is a custom `ComboButton`, not the `ComboButton` from this library, it is a little difficult to know what could be causing this issue. It's possible instead that the problem is related to the `OverflowMenu` usage/implementation in this custom `ComboButton` -- specifically, an upgrade in Carbon core (`carbon-components-react`) to the `OverflowMenu` that needs to be adjusted for. 🤔 

@IshratPahalwi feel free to send me a link to your code `ComboButton` in Slack if you need an extra set of eyes. 👍

**Comment by IshratPahalwi** [comment]
Replaced custom ComboButton with ComboButton from @carbon/ibm-security. The issue is resolved now. So closing this issue.
