### ISSUE TITLE
Bug - White box with no padding surrounding View more/View less no padding in Chrome

### ISSUE THREAD

**Issue by sharon-oboyle** [carbon-design-system/ibm-security#749]
## Bug - White box , with no padding on LHS surrounding View more/less control in Chrome

**Expected behavior -**

TBC: There is no white box surrounding the View more / View less text (to be consistent with behavoiur in other browsers)
If there is supposed to be a white box, there should be padding on the LHS so that the "V" can be read clearly

**Actual behavior -**

There is a white box surrounding the View more / View less text which is inconsistent with behavoiur in other browsers)
There is no padding on the LHS so that the white box is overlapping the "V"
<img width="273" alt="image" src="https://user-images.githubusercontent.com/56437682/92369240-a9371c80-f0f0-11ea-8a67-6f7b1f8caa33.png">
<img width="260" alt="image" src="https://user-images.githubusercontent.com/56437682/92369256-af2cfd80-f0f0-11ea-941d-df79c1c20a9d.png">

### Steps for reproducing

1. On https://ibm-security.carbondesignsystem.com/?path=/story/patterns-filterpanel--default component, open the truncated accordion
2. Note the View more text does not have any white box around it
3. Click View more
4. Note the View less text - has a white box around it
5. Click View less
6. Note the View more text - has a white box around it

### Affected browsers

Chrome (Version 85.0.4183.83 (Official Build) (64-bit))

Note: The following browsers were also tested and do not have a white box surounding the View more/View less control:
Edge (Version 85.0.564.44 (Official build) (64-bit)) 
Firefox (80.0.1 (64-bit))
Safari (Version 13.1.2 (15609.3.5.1.3))

**Comment by SimonFinney** [comment]
Hi @sharon-oboyle  - thanks for raising! I believe this may be related to how each of the browsers interpret whether a `button` element should receive focused when it has been selected.

Does the following information reflect the behaviour you've observed above? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus

**Comment by SharonOBoyle** [comment]
Hi @SimonFinney, apologies I seem to have missed responding to your message!  OK, yes I see the behaviour is reflected in that Firefox and Safari browsers are not showing the focus on selection.  

A remaining question though is when there is focus on the button would you expect there to be padding on the LHS between the focus box and the text inside the box?  Currently there appears to be no padding, so that the white box is nearly overlapping the V in the example below:

![image](https://user-images.githubusercontent.com/39183672/95716598-9bcb0000-0c63-11eb-8ca4-ae52cf32d660.png)

**Comment by SimonFinney** [comment]
No problem! I believe this is intended - @diego-codes could you confirm?

**Comment by diego-codes** [comment]
The button text needs to be aligned with the checkboxes above. The current solution is to remove all of the padding on that button, but maybe we can give the outline some spacing while maintaining the text alignment? What do you think @SimonFinney?

**Comment by SimonFinney** [comment]
We may face some maintenance issues because as well as an `outline-offset`, it would also require us to redefine Carbon's `box-shadow` value, making this brittle should the focus state change:

<img width="556" alt="border : box-shadow" src="https://user-images.githubusercontent.com/3846874/95838763-15cdb880-0d3a-11eb-912f-9728f4bd705d.png">

Alternatively, we could do something like the following, but that also feels kind of hacky and is prone to breaking should the button's padding change:

<img width="1111" alt="FilterPanel" src="https://user-images.githubusercontent.com/3846874/95838304-888a6400-0d39-11eb-86fb-49a1076b0e66.png">

It's questionable how much either of these styles from Carbon will actually change in practice, but the second solution seems like a quicker and easier fix.

@petervachon I'm curious to hear your thoughts on how this could behave from a design perspective?
