### ISSUE TITLE
onClick doesn't seem to be working for navItems

### ISSUE THREAD

**Issue by clairek20** [carbon-design-system/ibm-security#784]
## Bug 
When i add the onClick event listener it doesn't seem to do anything

**Comment by Yohanna** [comment]
My team also has a use case for this functionality.

We have a section in the Toolbar for User Preferences, like Theme, that opens up in a Modal on the same page. The only way to trigger that Modal would be through an `onClick` handler.

![image](https://user-images.githubusercontent.com/6926228/96460038-cc291600-11f0-11eb-90e7-2e708696e430.png)

![image](https://user-images.githubusercontent.com/6926228/96460086-d77c4180-11f0-11eb-892d-d47be8317d46.png)

We previously had a hack to trigger a handler function by setting the `href` to:
```
javascript:void(window.dispatchEvent(new Event("openUserPreferences")));
```

And then listening for that event and triggering the Modal accordingly. However, this workaround started failing recently due to the Content Security Policy.

Our feature is currently blocked till this functionality is implemented.
