### ISSUE TITLE
Inconsistent re-sizing of MultiSelect component

### ISSUE THREAD

**Issue by JennChao** [carbon-design-system/ibm-security#840]
## Bug - Inconsistent re-sizing of MultiSelect component

**Expected behavior -**

Width of MultiSelect component should be fixed instead of changing dynamically based on selected options.

**Actual behavior -**

![Re-sizing of Data sources selection drop-down in DE](https://user-images.githubusercontent.com/23396970/99350627-d1ee4600-28d9-11eb-8d03-fc938b4e3591.gif)

### Steps for reproducing

[CodeSandbox](https://codesandbox.io/s/)

1.  
2.  
3.  

#### 

![]()

#### 

![]()

#### 

![]()

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

- [ ]  / 
- [ ]  / 
- [ ]  / 

### Optional information

**Version -**

**Comment by JennChao** [comment]
@SimonFinney 
This issue was found in `"@carbon/ibm-security": "^1.25.0"`. Could you please help and check whether it has already been fixed in current carbon security version, `1.35.1-prerelease.1`. Thanks a lot.

**Comment by JennChao** [comment]
This issue still exists. Any update? @SimonFinney

**Comment by SimonFinney** [comment]
Because `MultiSelect` is a Carbon-maintained component, my recommendation is to create a reduced test case for this using https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox and submit an issue (https://github.com/carbon-design-system/carbon/issues/new?assignees=&labels=type%3A+bug+%F0%9F%90%9B&template=bug-report.md&title=) in that repo
